#-------------------------------------
#- Basic setup
#-------------------------------------
dataset: aqualoc                                          # dataset [kitti_odom, kitti_raw, tum-1/2/3, adelaide1/2]
seed: 4869                                                # random seed
image:
    height: 480                                           # image height
    width: 752                                            # image width
    ext: png                                              # image file extension for data loading
seq: 1                                     # sequence to run
frame_step: 1                                             # frame step
seq_len: 1
cam_mode: mono                                            # camera mode: [mono, stereo]
resize: 
crop_box: 
grayscale: False

#-------------------------------------
#- Directories
#-------------------------------------
directory:
    result_dir: ../saved/results/releVO/Aqualoc/Archaeological_site_sequences/1                       # directory to save result
    img_seq_dir: /home/olaya/Datasets/Aqualoc/Archaeological_site_sequences/archaeo_sequence_1_raw_data/raw_data/images_sequence_1       # image data directory
    gt_pose_dir: /home/olaya/Datasets/Aqualoc/Archaeological_site_sequences  # (optional) ground-truth pose data directory
    sequence_number: 1
    depth_dir:                                            # (optional) external depth data, e.g. ground-truth depths
