# This configuration corresponds to 
# the Reference Model in the extended version.

#-------------------------------------
#- Basic setup
#-------------------------------------
dataset: euroc                                            # dataset [kitti_odom, kitti_raw, tum-1/2/3, adelaide1/2]
image:
    height: 480                                           # image height
    width: 752                                            # image width
    ext: png                                              # image file extension for data loading
seq: MH_04_difficult                                     # sequence to run
frame_step: 1                                             # step between consecutive frames
seq_len: 4                                                # length of frame sequence 
cam_mode: mono                                            # camera mode: [mono, stereo]
resize: ~
crop_box: ~
grayscale: False
#-------------------------------------
#- Directories
#-------------------------------------
directory:
    result_dir: ../saved/results/DFVO/EuRoC/MH_04_difficult                       # directory to save result
    img_seq_dir: /home/olaya/Datasets/EuRoC/MH_04_difficult/mav0/cam0       # image data directory
    gt_pose_dir: /home/olaya/Datasets/EuRoC/MH_04_difficult/mav0/state_groundtruth_estimate0  # (optional) ground-truth pose data directory
    depth_dir:                                            # (optional) external depth data, e.g. ground-truth depths