#-------------------------------------
#- Basic setup
#-------------------------------------
dataset: mimir                                            # dataset [kitti_odom, kitti_raw, tum-1/2/3, adelaide1/2]
seed: 4869                                                # random seed
image:
    height: 480                                           # image height
    width: 720                                            # image width
    ext: png                                              # image file extension for data loading
seq: ${sequence_name}                                     # sequence to run
frame_step: 1                                             # frame step
cam_mode: mono                                            # camera mode: [mono, stereo]

#-------------------------------------
#- Directories
#-------------------------------------
directory:
    result_dir: ${result_directory}                       # directory to save result
    img_seq_dir: ${dataset_directory}/${sequence_name}/${track}/auv0/rgb/cam0        # image data directory
    gt_pose_dir: ${dataset_directory}/${sequence_name}/${track}/auv0/pose_groundtruth  # (optional) ground-truth pose data directory
    depth_dir:                                            # (optional) external depth data, e.g. ground-truth depths

