  name: relevo
  channels:
    - pytorch
    - conda-forge
    - anaconda
  dependencies:
    - python=3.10
    - pytorch=1.13.1
    - torchvision
    - jupyter
    - tensorboard
    - opencv=4.6.0
    - scipy
    - scikit-image
    - tqdm
    - tensorboardx
    - pip
    - pip:
        - pykitti
        - colour_demosaicing
        - pyyaml
        - open3d 
        - easydict
        - PyYAML
        - pandas