# This configuration corresponds to 
# the Reference Model in the extended version.

#-------------------------------------
#- Basic setup
#-------------------------------------
dataset: ${tum_room}                                      # dataset [kitti_odom, kitti_raw, tum-1/2/3, adelaide1/2]
seed: 4869                                                # random seed
image:
    height: 480                                           # image height
    width: 640                                            # image width
    ext: png                                              # image file extension for data loading
seq: ${sequence_name}                                     # sequence to run
frame_step: ${frame_step}                                             # frame step
seq_len: ${seq_len}                                       # length of frame sequence 
cam_mode: mono                                            # camera mode: [mono, stereo]
resize: ${resize}
crop_box: ${crop_box}
grayscale: ${grayscale}
#-------------------------------------
#- Directories
#-------------------------------------
directory:
    result_dir: ${result_directory}                       # directory to save result
    img_seq_dir: ${dataset_directory}       # image data directory
    gt_pose_dir: ${dataset_directory}  # (optional) ground-truth pose data directory
    depth_dir:                                            # (optional) external depth data, e.g. ground-truth depths

#-------------------------------------
#- Depth
#-------------------------------------
depth:                                                    # Depth configuration
    depth_src: ~
