# This configuration corresponds to Ablation study

#-------------------------------------
#- Basic setup
#-------------------------------------
dataset: tum-1                                            # dataset [kitti_odom, kitti_raw, tum-1/2/3, adelaide1/2]
image:
    height: 480                                           # image height
    width: 640                                            # image width
    ext: png                                              # image file extension for data loading
seq: rgbd_dataset_freiburg1_360       # sequence to run
frame_step: 1
seq_len: 4                                                # length of frame sequence 
cam_mode: mono                                            # camera mode: [mono, stereo]
resize: ~
crop_box: ~
grayscale: False
#-------------------------------------
#- Directories
#-------------------------------------
directory:
    result_dir: /home/olaya/Datasets/TUM/rgbd_dataset_freiburg1_360/                             # directory to save result
    img_seq_dir: /home/olaya/Datasets/TUM              # image data directory
    gt_pose_dir: /home/olaya/Datasets/TUM                                        # (optional) ground-truth pose data directory
    depth_dir: ~
#-------------------------------------
#- Depth
#-------------------------------------
depth:                                                    # Depth configuration
    depth_src: ~