#-------------------------------------
#- Basic setup
#-------------------------------------
dataset: mimir                                            # dataset [kitti_odom, kitti_raw, tum-1/2/3, adelaide1/2]
seed: 4869                                                # random seed
image:
    height: 480                                           # image height
    width: 720                                            # image width
    ext: png                                              # image file extension for data loading
seq: SeaFloor                                     # sequence to run
frame_step:                                              # frame step
seq_len: 4                                       # length of frame sequence 
cam_mode: mono                                            # camera mode: [mono, stereo]
resize: 
crop_box: 
grayscale: False
#-------------------------------------
#- Directories
#-------------------------------------
directory:
    result_dir: ../saved/results/releVO/MIMIR/SeaFloor/track1                       # directory to save result
    img_seq_dir: /home/olaya/Datasets/MIMIR/SeaFloor/track1/auv0/rgb/cam0        # image data directory
    gt_pose_dir: /home/olaya/Datasets/MIMIR/SeaFloor/track1/auv0/pose_groundtruth  # (optional) ground-truth pose data directory
    depth_dir:                                            # (optional) external depth data, e.g. ground-truth depths

