# This configuration corresponds to 
# the Reference Model in the extended version.

#-------------------------------------
#- Basic setup
#-------------------------------------
dataset: mimir                                            # dataset [kitti_odom, kitti_raw, tum-1/2/3, adelaide1/2]
seed: 4869                                                # random seed
image:
    height: 480                                           # image height
    width: 720                                            # image width
    ext: png                                              # image file extension for data loading
seq: SeaFloor                                     # sequence to run
frame_step: 1                                             # frame step
seq_len: 4                                                # length of frame sequence 
cam_mode: mono                                            # camera mode: [mono, stereo]
resize: ~
crop_box: ~
grayscale: False
#-------------------------------------
#- Directories
#-------------------------------------
directory:
    result_dir: ../results/DFVO/MIMIR/SeaFloor/track0                       # directory to save result
    img_seq_dir: /home/olaya/Datasets/MIMIR/SeaFloor/track0/auv0/rgb/cam0        # image data directory
    gt_pose_dir: /home/olaya/Datasets/MIMIR/SeaFloor/track0/auv0/pose_groundtruth  # (optional) ground-truth pose data directory
    depth_dir:                                            # (optional) external depth data, e.g. ground-truth depths