#-------------------------------------
#- Basic setup
#-------------------------------------
dataset: kitti_odom                                            # dataset [kitti_odom, kitti_raw, tum-1/2/3, adelaide1/2]
seed: 4869                                                # random seed
image:
    height: 370                                           # image height
    width: 1226                                           # image width
    ext: png                                              # image file extension for data loading
seq: ${sequence_name}                                     # sequence to run
frame_step: 1                                             # frame step
cam_mode: mono                                            # camera mode: [mono, stereo]

#-------------------------------------
#- Directories
#-------------------------------------
directory:
    result_dir: ${result_directory}                       # directory to save result
    img_seq_dir: ${dataset_directory}/data_odometry_color/dataset/sequences       # image data directory
    gt_pose_dir: ${dataset_directory}/data_odometry_poses/dataset/poses   # (optional) ground-truth pose data directory
    depth_dir:                                            # (optional) external depth data, e.g. ground-truth depths