#-------------------------------------
#- Basic setup
#-------------------------------------
dataset: mimir                                            # dataset [kitti_odom, kitti_raw, tum-1/2/3, adelaide1/2]
n_gpu: 'cuda:0'
model:
    type: DeepVOModel
    args:
        batchNorm: true
        conv_dropout: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.5]
        image_size: [480,752]
        rnn_hidden_size: 1000
        rnn_dropout_out: 0.5
        rnn_dropout_between: 0
        checkpoint_location: [saved/checkpoints/FlowNet2_checkpoint.pth.tar]
data_loader:
    dataset_dirs: [
          "SeaFloor/track0",
          "SeaFloor/track1"    
        ]
    batch_size: 8
    num_workers: 4
    shuffle: true
    target_image_size: [480,752]


optimizer:
    type: Adam
    args:
        lr: 0.001
        weight_decay: 0
        amsgrad: true


#-------------------------------------
#- Directories
#-------------------------------------
trainer: 
    epochs: 200
    save_dir: "saved/deepvo/mimir"
    save_period: 1
    monitor: "min mse_metric"
    tensorboard: true
    metrics: ["mse_euler_position_metric", "mse_euler_rotation_metric"]
